config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users #deveiseを使用する際urlにusersを含むことの意味
  root to: "homes#top"
  
  #resourcesメソッドでルーティングを生成
  #onlyオプションで生成するルーティングを限定
  #booksコントローラにbooks_commentsコントローラをネストする(親子関係)
  #ネストすることでurlを作成しparams[:book_id]でBookのidが取得できるようになる(rails routes参照)
  resources :books, only: [:index, :show, :create, :destroy] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end 
  resources :users, only: [:show, :edit, :update]
  get 'homes/about' => "homes#about", as: 'about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  #Bookモデルにtitleとbodyに加えて画像を扱うためのimageカラムを追加
  has_one_attached :image
  
  #Userモデルとのアソシエーション
  #1人のユーザが複数投稿できる(1:N)
  belongs_to :user
  
  #BookCommentモデルとのアソシエーション
  #1個の投稿に複数のコメントができる(1:N)
  has_many :book_comments, dependent: :destroy
  
  #Favoriteモデルとのアソシエーション
  #1個の投稿に複数のいいねができる(1:N)
  has_many :favorites, dependent: :destroy
  
  #favorited_by?メソッドで引数に渡されたユーザidがFavoritesテーブル内に存在するかを判定
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end 
  
  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200 }
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  
  #Userモデル,Bookモデルとのアソシエーション
  belongs_to :user
  belongs_to :book
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  #BookモデルとUserモデルとのアソシエーション
  belongs_to :book
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  #Bookモデルとのアソシエーション
  #[1:N]の[1]側がhas_manyになる
  #複数のBookモデルと関連付けるために複数形
  has_many :books, dependent: :destroy
  
  #BookCommentモデルとのアソシエーション
  #1人のユーザが複数コメントできる(1:N)
  has_many :book_comments, dependent: :destroy
  
  #Favoriteモデルとのアソシエーション
  #1人のユーザが複数のいいねができる(1:N)
  has_many :favorites, dependent: :destroy
  
  #プロフィール画像を保存できるように設定
  has_one_attached :profile_image
  
  #画像表示するための記述
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end 
    profile_image.variant(resize_to_limit: [width, height]).processed
  end 
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #devise利用の機能(ユーザ登録、ログイン認証など)が行われる前にconfigure_permitted_parametersメソッドが実行される
  before_action :configure_permitted_parameters, if: :devise_controller?
  #ログイン認証が成功していないと、トップページ以外の画面を表示させない
  before_action :authenticate_user!, except: [:top]
  
  #サインイン後の遷移先を設定
  #after_sign_in_path_forはdevise側のメソッド
  def after_sign_in_path_for(resource)
    books_path
  end 
  
  #サインアウト後の遷移先を設定
  def after_sign_out_path_for(resource)
    about_path
  end 
  
  #protectedは呼び出された他のコントローラからも参照可能
  protected
  
  #configure_permitted_parametersメソッドでは
  #devise_parameter_sanitizer.permitメソッドを使うことでデータの操作を行う
  #devise_parameter_sanitizer.permit(:deviseの処理名, keys: [:許可するキー])
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end 
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  
  #コメントの作成
  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_to book_path(book)
  end 
  
  #コメントの削除
  def destroy
    BookComment.find(params[:id]).destroy
    redirect_to book_path(params[:book_id])
  end 
  
  private
  
  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end 
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  #投稿データの保存
  def create
    @book = Book.new(book_params) #投稿するデータをBookモデルに紐づくデータとして保存する準備をしていてフォームに入力された(title,body)が@bookに格納される
    @book.user_id = current_user.id #投稿者id(@book.user_id)をログイン中のユーザのidを持たせる
    if @book.save
     redirect_to books_path
    else 
     @books = Book.all
     @user = User.find(current_user.id)
     render :index
    end 
  end 
  

  def index
    @books = Book.all
    @book = Book.new
    @user = User.find(current_user.id)
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @book_comment = BookComment.new #コメントを投稿するためのインスタンス変数
  end
  
  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end 
  
  #投稿データのストロングパラメータ
  private
  
  def book_params
    params.require(:book).permit(:title, :body)
  end 
  
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  
  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_to books_path
  end
  
  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id) 
    favorite.destroy
    redirect_to books_path
  end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end 
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    #全体の投稿ではなく、個人の投稿を取得する
    @books = @user.books #アソシエーションを持っているモデル同士の記述
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end 
  
  private
  
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/_form.html.erb
<%= form_with model: [book, book_comment] do |f| %>
 <%= f.text_area :comment, rows: '5', placeholder: "コメントをここに" %>
 <%= f.submit '送信' %>
<% end %>

app/views/books/_errors.html.erb
<% if obj.errors.any? %>
 <%= obj.errors.count %>件のエラーが発生しました
 <ul>
   <% obj.errors.full_messages.each do |message| %>
   <li>
     <%= message %>
   </li>
   <% end %>
 </ul>
<% end %>

app/views/books/_form.html.erb
<h1>New Book</h1>
<%= form_with model:book do |f| %>
 <%= f.label :title %><br>
 <%= f.text_field :title %><br>
 <%= f.label :body %><br>
 <%= f.text_area :body %><br>
 <%= f.submit 'Create Book' %>
<% end %>

app/views/books/index.html.erb
<% @books.each do |book| %> <!--コントローラから渡された@books変数内から1つずつ取り出して、book変数へ格納-->
<table>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Body</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= link_to user_path(@user) do %>
          <%=image_tag book.user.get_profile_image(100,100) %>
          <% end %><br>
          <%= link_to book.user.name, user_path(@user) %></td>
      <td><%= link_to book.title, book_path(book.id) %></td> <!--book変数のtitleカラムを表示.Bookモデルで定義済み-->
      <td><%= book.body %></td> <!--book変数のtitleカラムを表示.Bookモデルで定義済み-->
      <td><%= render 'favorites/favorite', book: @book %></td>
      <td><%= link_to "#{book.book_comments.count} コメント", book_path(book.id) %></td>
    </tr>
  </tbody>
</table>
<% end %>

<div>
  <%= render 'errors', obj: @book %>
  <%= render 'form', book: @book %>
</div>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<table>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Body</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= link_to user_path(@user.id) do %>
          <%= image_tag @user.get_profile_image(50,50) %>
          <% end %></td>
      <td><%= @book.title %></td>
      <td><%= @book.body %></td>
      
      <td><%= render 'favorites/favorite', book: book %></td>
      
      <td><%= @book.book_comments.count %>コメント</td>
      <td><% if @book_comment.user == current_user %>
          <%= link_to "destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete %>
          <% end %></td>
          
      <td><% if @book.user == current_user %>
          <%= link_to "destroy", book_path(@book), method: :delete %>
          <% end %></td>
    </tr>
  </tbody>
</table>
<%= render 'book_comments/form', book: @book, book_comment: @book_comment %>

app/views/favorites/_favorite.html.erb
<% if book.favorited_by?(current_user) %>
  <%= link_to book_favorites_path(book), method: :delete do %>
   ♥<%= book.favorites.count %>
  <% end %>
 <% else %>
  <%= link_to book_favorites_path(book), method: :post do %>
   ♡<%= book.favorites.count %>
  <% end %>
<% end %>

app/views/homes/about.html.erb
about

app/views/homes/top.html.erb
<h1>Homes#top</h1>
<p>Find me in app/views/homes/top.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2Review</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <!--FontAwesomeの導入記述(FontAwesomeのサイトからコピーする)-->
    <script src="https://kit.fontawesome.com/beac707b93.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!--動的なヘッダー作成
        link_toのHTTPメソッドは設定しなければGET
        ログアウトはHTTPメソッドがDELETE(rails routes参照)-->
    <header>
     <!-- ログインしているかどうかの判断(devise側のヘルパーメソッド)-->
     <% if user_signed_in? %>
      <li>
        <%= link_to "Home", root_path %>
      </li>
      <li>
        <%= link_to "Books", books_path %>
      </li>
      <li>
        <%= link_to "User", user_path(current_user.id) %>
      </li>
      <li>
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
      </li>
     <% else %>
      <li>
        <%= link_to "新規登録", new_user_registration_path %>
      </li>
      <li>
        <%= link_to "ログイン", new_user_session_path %>
      </li>
     <% end %>
    </header>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<h2>User Editting</h2>
<%= form_with model:@user do |f| %>
<table>
  <tr>
   <th><label for="inputName">Name</label></th>
   <td><%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前" %></td>
  </tr>
  <tr>
   <th><label for="inputIntroduction">Introduciton</label></th>
   <td><%= f.text_area :introduction, autofocus: true, id:"inputIntroduction" %></td>
  </tr>
  <tr>
   <th><label for="inputProfile_image">ProfileImage</label></th>
   <td><%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %></td>
  </tr>
</table>
 <%= f.submit "Update" %>
<% end %>

app/views/users/show.html.erb
<!--ユーザの詳細-->
<div>
  <%= image_tag @user.get_profile_image(100,100) %>
</div>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <td><%= @user.name %></td>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>Introduction</td>
      <td><%= @user.introduction %></td>
    </tr>
  </tbody>
</table>
<div>
  <%= link_to "プロフィール編集", edit_user_path %>
</div>

<!--新規投稿フォーム-->
<%= render 'books/form', book: @book %>
<!--ユーザの投稿一覧-->
<% @books.each do |book| %>
<table>
  <tr>
    <th></th>
    <th>Title</th>
    <th>Body</th>
    <th></th>
  </tr>
  <tr>
    <td><%= image_tag book.user.get_profile_image(50,50) %></td>
    <td><%= book.title %></td>
    <td><%= book.body %></td>
    <td><%= link_to "#{book.book_comments.count} コメント", book_path(book.id) %></td>
  </tr>
</table>
<% end %>